services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PORT
        value: 8080
